build website:
  stage: build
  script:
    - cd /home/vagrant/blog-projet4
    - make html
    - pelican content -o output -s pelicanconf.py

deploy website:
  stage: deploy
  when: manual
  only:
  - master
  script:
    - cd /home/vagrant/blog-projet4
    - make publish
    - pelican content -o output -s publishconf.py

# Copie des .html générés dans "output" pour Serveur Nginx
    - cp /home/vagrant/blog-projet4/output/*.html /var/www/blog.projet4/html
    - cp /home/vagrant/blog-projet4/output/*.html /var/www/daniel-sniecinski.github.io/html
   
# Envoi des.html vers Github Pages "daniel-sniecinski.github.io"
    - cd /home/vagrant/blog-projet4/output
    - git init
    - git remote add origin https://${GITHUB_TOKEN}@github.com/DANIEL-SNIECINSKI/daniel-sniecinski.github.io.git
    - git add .
    - git commit -m "Publish"
    - git push origin master --force




