
build website:
  stage: build
  script:
    - cd blog-projet4
    - make html
    - pelican content -o output -s pelicancon.py

deploy website:
  stage: deploy
  only:
  - master
  script:
    - make publish
    - pelican content -o output -s publishconf.py

